server:
  port: 8082
spring:
  application:
    name: "teachers"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/teacher_db
    username: springstudent
    password: springstudent
  config:
    import: "optional:configserver:http://localhost:8071/"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

teacher-service:
  url: http://localhost:8082

management:
  metrics:
    export:
      zipkin:
        enabled: true
  tracing:
    zipkin:
      enabled: true
      baseUrl: http://localhost:9411/