server:
  port: 8081
spring:
  application:
    name: students
  datasource:
    url: jdbc:mysql://localhost:3306/student_tracker
    username: springstudent
    password: springstudent
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
