server:
  port: 8082
spring:
  application:
    name: teachers
  datasource:
    url: jdbc:mysql://localhost:3306/teacher_db
    username: springstudent
    password: springstudent
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
