server:
  port: 8081
spring:
  application:
    name: "students"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/student_tracker
    username: springstudent
    password: springstudent
  config:
    import: "optional:configserver:http://localhost:8071/"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    export:
      zipkin:
        enabled: true
  tracing:
    zipkin:
      enabled: true
      baseUrl: http://localhost:9411/

