server:
  port: 8090
spring:
  application:
    name: "apigateway"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    enable: true
  info:
    env:
      enabled: true
info:
  app:
    name: "apigateway"
    description: "Tech-Teaching Gateway Server Application"
    version: "1.0.0"

